"""Generate readable v1.18 specifications from authored JSON, without runtime writes."""
from __future__ import annotations

from collections import Counter, defaultdict
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def read(path: str):
    return json.loads((ROOT / path).read_text(encoding="utf-8"))


def cell(value) -> str:
    if isinstance(value, list):
        return "; ".join(cell(v) for v in value)
    if isinstance(value, dict):
        return "; ".join(f"{k}: {cell(v)}" for k, v in value.items())
    return str(value).replace("|", "/").replace("\n", " ")


def table(headers, rows) -> str:
    return "\n| " + " | ".join(headers) + " |\n| " + " | ".join("---" for _ in headers) + " |\n" + "".join("| " + " | ".join(cell(v) for v in row) + " |\n" for row in rows) + "\n"


def fields(data) -> str:
    return table(["Field", "Contract / value"], [(k.replace("_", " "), v) for k, v in data.items()])


def build() -> dict[str, bytes]:
    roster = read("docs/product-specs/roster/hero_roster.json")
    mapping = read("docs/product-specs/roster/oracle_mapping.json")
    refs = read("docs/references/visual/v1.18/reference_inventory.json")
    dupes = read("docs/references/visual/v1.18/reference_duplicates.json")
    heroes = roster["heroes"]
    launch = [h for h in heroes if h["selection"]["status"] == "launch"]
    reserve = [h for h in heroes if h["selection"]["status"] == "reserve"]
    result: dict[str, str] = {}
    prefix = "<!-- Generated by tools/art/roster_lock.py; edit the referenced JSON, then rebuild. -->\n\n"
    doc = "# Launch roster and candidate classification v1\n\n" + roster["scope"] + "\n\n" + roster["decision_authority"] + "\n\n"
    doc += "Authored source: `hero_roster.json`. All eight original fields remain at each source pointer. Names, species, title, role, personality and weapon style are sourced; gender/presentation is unresolved for all 20. All body, motion, material, rig and height details under `design_proposal` are explicitly proposals. Branch aliases are normalized exactly once.\n\n"
    doc += "## 16 launch heroes\n" + table(["ID / sheet", "Name", "Species", "Primary / secondary", "Why launch"], [(f"[{h['id']}](heroes/{h['id']}.md)", h["identity"]["canonical_name"], h["identity"]["species"], h["identity"]["primary_branch"] + " / " + h["identity"]["secondary_branch"], h["selection"]["decision"]) for h in launch])
    doc += "## 4 reserve heroes\n" + table(["ID", "Name", "Branches", "Why reserve"], [(h["id"], h["identity"]["canonical_name"], [h["identity"]["primary_branch"], h["identity"]["secondary_branch"]], h["selection"]["decision"]) for h in reserve])
    doc += "## All-candidate production audit (proposals)\n" + table(["Candidate", "Body / silhouette", "Speed / weight / range", "Rig / complexity", "Differentiation", "Reference / rights"], [(h["id"], [h["design_proposal"]["visual"][k] for k in ["body_type", "silhouette"]], [h["design_proposal"]["visual"][k] for k in ["speed_impression", "weight_impression", "range_impression"]], [h["design_proposal"]["visual"][k] for k in ["rig_family", "complexity"]], h["design_proposal"]["visual"]["distinctive_feature"], f"{h['references']['primary']}; unknown-rights; incomplete") for h in heroes])
    doc += "## Supporting candidate fields\n\nReserve candidates are fully retained in JSON, including VFX, source-backed personality/weapon/archetype, motion proposal, reference views and unresolved decisions. No legacy or runtime hero ID is removed or rewritten. Selection is not permission to model from an uncleared image.\n"
    result["docs/product-specs/roster/LAUNCH_ROSTER.md"] = doc
    score = "# Roster scoring matrix\n\n" + roster["selection_policy"] + "\n\n" + roster["scoring_rubric"]["scale"] + "\n\nAll weights are 1. Rights are 0 for everyone and cannot be offset by a high total. The total is an ordinal comparison, not a production-readiness gate.\n"
    criteria = list(roster["scoring_rubric"]["criteria"])
    score += table(["Criterion", "Rubric"], roster["scoring_rubric"]["criteria"].items())
    for chunk in [criteria[:8], criteria[8:]]:
        score += table(["Candidate"] + chunk + ["Total / 75", "Decision"], [(h["id"], *[h["scoring"][k] for k in chunk], sum(h["scoring"].values()), h["selection"]["status"]) for h in heroes])
    score += "## Decision rationale\n\nBrumgar and Elunor both stay despite their duplicate unordered Guardian/Healing pair: only two sourced Healing candidates exist, and brawler versus ritual healer is a useful distinction. The same coverage constraint retains both Toxin candidates despite Sylvex/Skarvex extension costs. Oromir is mandatory for Ice. Four reserves primarily reduce redundant melee pressure, heavy fists/hammer and Precision/Dodge blades. Unknown rights do not favor the best-looking picture: even Solkael remains blocked at production entry.\n"
    result["docs/product-specs/roster/SCORING_MATRIX.md"] = score
    branches = ["Assault", "Guardian", "Essence", "Rage", "Ice", "Toxin", "Shield", "Healing", "Power", "Precision", "Wound", "Dodge"]
    counts = Counter(b for h in launch for b in (h["identity"]["primary_branch"], h["identity"]["secondary_branch"]))
    doc = "# Branch × launch hero coverage\n\nP = sourced first affinity; S = sourced second affinity. The order is a presentation convention, not a new combat rule.\n"
    doc += table(["Branch", "Count"] + [h["id"].split("_")[0] for h in launch], [(b, counts[b], *["P" if h["identity"]["primary_branch"] == b else "S" if h["identity"]["secondary_branch"] == b else "—" for h in launch]) for b in branches])
    doc += "Ice is underrepresented (1): only Oromir has sourced Ice/Frost. Adding an unsourced second affinity would alter concept data, so no such change is made. Precision and Essence are most represented (4 each), split between distinct weapons and roles. Every other branch has 2–3 entries. Counts measure identity coverage, not combat power or balance.\n\n"
    pairs = defaultdict(list)
    for h in launch:
        pairs[tuple(sorted([h["identity"]["primary_branch"], h["identity"]["secondary_branch"]]))].append(h["id"])
    doc += "## Duplicate unordered pairs\n" + table(["Pair", "Heroes", "Treatment"], [(pair, ids, "Sustain brawler versus ritual healer; retain both to avoid single-hero Healing dependency.") for pair, ids in pairs.items() if len(ids) > 1])
    doc += "## Similar archetypes\n\nSolkael/Brumgar/Rhazgor share defensive mass: distinguish gauntlet counter, rounded fist sustain and shield/horn siege. Kitsara/Lupika share agility: daggers and deceptive pivots versus heel strikes and spring steps. Aethryon/Oromir/Morvayne share casting: spear-line charge, clock-ring control and rapier sigils. Sylvex/Skarvex share Toxin: coiled mist attrition versus overhead stinger puncture. Do not solve overlap by changing stats in this phase.\n"
    result["docs/product-specs/roster/BRANCH_COVERAGE.md"] = doc
    labels = {"exact conceptual replacement": "E", "strong match": "S", "partial match": "P", "no match": "—"}
    doc = "# 16 oracle → 20 candidate migration matrix\n\n" + mapping["scope"] + "\n\nE = exact conceptual replacement; S = strong match; P = partial match; — = no match. Full 320 cell-specific reasons are in `oracle_mapping.json`.\n" + fields(mapping["rating_rules"])
    # Split horizontally so all 20 columns are readable in ordinary Markdown viewers.
    for group in [heroes[:10], heroes[10:]]:
        doc += table(["Oracle"] + [h["id"].split("_")[0] for h in group], [(o["oracle_id"], *[labels[next(c for c in o["cells"] if c["candidate_id"] == h["id"])["rating"]] for h in group]) for o in mapping["oracles"]])
    doc += "## Preservation and merge/split decisions\n" + table(["Oracle", "Primary / complementary", "Gameplay need preserved", "Merge/split and limits"], [(o["oracle_id"], [o["primary_candidate"], *o["complementary_candidates"]], o["preservation_requirement"], o["merge_split"]) for o in mapping["oracles"]])
    doc += "## Compatibility rule\n\nAll 16 oracle IDs remain executable fixtures with their exact current stats, branch pairs, skill types, timings and replay history. The 20 candidate IDs are a separate production-identity namespace. A future visual binding may be many-to-one but must never merge combat identity or silently alias saves/replays. Six unmatched oracle branch pairs (Ice/Precision, Wound/Assault, Toxin/Dodge, Assault/Guardian, Power/Essence, Dodge/Healing) remain explicit combined-kit gaps. Systemic role/branch coverage is preserved across the launch roster; combined-kit equivalence is not claimed. Any later data replacement needs a versioned spec, full old/new hero comparison, malformed-ID tests, seeded outcomes and migration/replay compatibility checks.\n"
    result["docs/product-specs/roster/ORACLE_MIGRATION_MATRIX.md"] = doc
    for h in launch:
        d = h["design_proposal"]
        doc = f"# {h['identity']['canonical_name']} — identity sheet\n\nID: `{h['id']}`. Launch. Source: `../hero_roster.json`, `{h['source']['pointer']}` in the exact legacy snapshot.\n\n"
        doc += "## Identity (sourced)\n" + fields(h["identity"])
        doc += "## Visual direction (proposal)\n\n" + d["basis"] + "\n" + fields(d["visual"])
        doc += "## Combat presentation (proposal)\n" + fields(d["combat_presentation"])
        doc += "## VFX (proposal)\n" + fields(d["vfx"])
        doc += "## Production\n" + fields({"rig_family": d["visual"]["rig_family"], "unique_rig_requirements": d["visual"]["unique_rig_requirements"], "height_m_proposal": d["height_m_proposal"], "weapon_sockets": d["weapon_sockets"], "vfx_sockets": d["vfx_sockets"], "complexity": d["visual"]["complexity"], "expression_deviation": d["expression_deviation"], "primary_reference": h["references"]["primary"], "supporting_reference": h["references"]["supporting"], "rights_status": h["references"]["rights_status"], "production_ready": False})
        doc += "Rig, names, markers and axes follow `docs/art/CHARACTER_PRODUCTION_BIBLE.md`. Motion and range impressions never change resolver statistics.\n"
        doc += "## Reference coverage\n" + table(["View", "Status", "Reference", "Gap / limitation"], [(v, row["status"], row["reference_ids"], row["reason"]) for v, row in h["references"]["coverage"].items()])
        doc += "## Unresolved before production\n\n" + "\n".join("- " + item for item in h["unresolved"]) + "\n"
        result[f"docs/product-specs/roster/heroes/{h['id']}.md"] = doc
    gaps = "# Unresolved visual decisions and reference gaps\n\nG = missing dedicated view; P = partial concept only, not production-ready. All 20 candidates remain rights-blocked for pixel reuse. A complete classification is not a claim that reference packets exist.\n"
    gaps += table(["Hero", "Roster"] + roster["required_reference_views"], [(h["id"], h["selection"]["status"], *["P" if h["references"]["coverage"][v]["status"] == "partial-reference" else "G" for v in roster["required_reference_views"]]) for h in heroes])
    gaps += "For the 16 launch heroes, 49 view slots have partial reference and 111 have no adequate dedicated view; zero of 160 slots are certified production-ready. Missing across the launch: front, side, back, isolated silhouette, consistent combat stance and expression sheet. Weapon details are missing except partial Solkael gauntlets. The three common partial slots are neutral, 3/4 front and palette.\n\n"
    gaps += "## Source conflicts resolved for specification\n\n- Textual identity/affinities win over erroneous branch badges in roster art. Arcane→Essence, Venom→Toxin, Frost→Ice; other invented branch names are rejected.\n- Solkael uses sourced tower gauntlets, not swords from unnamed lion studies.\n- The white ice-wolf sheets are not identified as Fenrox and do not add Ice affinity.\n- Candidate boards change anatomy (snake legs/coil, eagle arms/full bird, panther biped/quadruped, mantis human/insect). Proposed stable morphologies are explicit in sheets; stage-driven topology changes are not approved.\n- Images label evolution unlock levels, Rare/Mythic and extra branch names. None change economy, levels, rarity or the 150-card dataset.\n- No source defines gender/presentation or voice. All remain unresolved, including apparently gendered names and drawings.\n\n"
    gaps += "## Decisions required at v1.19 entry\n\nEstablish provenance/license or create independently authored original design without reusing uncleared pixels. Complete consistent minimum views; record approved morphology, dimensions, dominant hand, palm/socket orientation, tail/wing extents and facial-control mapping. Choose a licensed shipping font and original branch glyphs. These are preflight work for v1.19, not permission to begin final modeling now.\n\n"
    gaps += "## Preserved balance signals\n\nThe v1.17 report remains authoritative: Shield/healing scenario 04 had 100% timeout; skill scenario 08 about 99%; Toxin scenario 05 averaged 6.136 s with 95/1000 draws; cross-order scenarios 11/12 about 5.999 s with 100% B wins. These are untuned fixture observations, not roster score inputs. No gameplay values change. See `docs/qa/V1_17_BALANCE_REPORT.md` for all metrics and limitations.\n"
    result["docs/art/UNRESOLVED_AND_REFERENCE_GAPS.md"] = gaps
    rights = Counter(i["rights_status"] for i in refs["items"])
    doc = "# Reference rights review v1.18\n\nThe inventory classifies every origin and retains all unknown material at existing legacy/reference paths, outside production asset admission. Physical deletion/moving is unnecessary. Author/owner remains unknown; tool-name filenames are not ownership or license evidence. This is an evidence audit, not a legal clearance opinion.\n" + table(["Class", "Groups"], [(r, rights[r]) for r in refs["rights_classes"]])
    doc += f"{len(refs['items'])} content groups; {dupes['origins']} origins; {dupes['duplicate_groups']} duplicate-content groups; {dupes['duplicate_extra_origins']} extra origins. Historical working-byte SHA and canonical Git-blob SHA are distinct where line endings differ. No image moved, copied, edited or deleted.\n\n"
    doc += "## Limited direction selections\n" + table(["Stable reference ID", "Source", "Selected use", "Rights / production"], [(i["id"], i["source"], i["notes"], "unknown-rights / blocked") for i in refs["items"] if i["approval_status"] == "direction-selected"])
    doc += "## Admission rule\n\n`production-approved` requires owned-original, generated-for-project or licensed status, an explicit evidence record identifying owner/license/generation provenance and permitted use, and production_usable=true. Unknown, third-party-reference-only and prohibited-for-production never pass. Dota/Valve art cannot pass from stylistic usefulness. `direction-selected` permits limited internal planning only and never satisfies production admission. Classification changes require source evidence and a reviewed manifest change.\n"
    result["docs/references/visual/v1.18/RIGHTS_REVIEW.md"] = doc
    for name, title in [("rig_families", "Rig families v1"), ("character_conventions", "Blender/Godot character conventions"), ("animation_contract", "Animation contract v1"), ("expression_library", "Expression Library v1"), ("brand_ui_language", "Brand & UI Language v1"), ("card_visual_language", "Card Visual Language v1")]:
        data = read(f"docs/art/{name}.json")
        doc = f"# {title}\n\nMachine-readable authority: `{name}.json`. No final asset or runtime implementation is created by this specification.\n"
        for key, value in data.items():
            doc += "\n## " + key.replace("_", " ").title() + "\n\n"
            if isinstance(value, list) and value and isinstance(value[0], dict):
                for row in value:
                    doc += fields(row)
            elif isinstance(value, dict):
                doc += fields(value)
            else:
                doc += cell(value) + "\n"
        result[f"docs/art/{name.upper()}.md"] = doc
    return {p: (prefix + doc).encode("utf-8") for p, doc in result.items()}


def main():
    for path, content in build().items():
        target = ROOT / path
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(content)
    print("Generated roster/matrices, 16 identity sheets, production contracts and rights/gap reports.")


if __name__ == "__main__":
    main()
